server:
  port: 8083
spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true #可以设置多个调用相同的微服务 @FeignClient(name = "item-service")
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.58.132:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
