server:
  port: 8084
spring:
  application:
    name: goodsdetail-service
  main:
    allow-bean-definition-overriding: true #可以设置多个调用相同的微服务 @FeignClient(name = "item-service")
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10